# Generated by Django 2.2.7 on 2019-12-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('collage_NO', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
