# Generated by Django 3.0.2 on 2020-01-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financestatues',
            options={'base_manager_name': 'objects'},
        ),
    ]
