# Generated by Django 2.2.7 on 2019-12-04 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('semester_count', models.IntegerField()),
                ('courses', models.TextField()),
                ('degree', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScientificStatues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GPA', models.TextField()),
                ('GPA_details', models.TextField()),
                ('dep_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Program.Program')),
                ('std_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student')),
            ],
        ),
    ]
