# Generated by Django 2.2.5 on 2019-12-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientificstatues',
            name='GPA',
        ),
    ]
