# Generated by Django 2.2.5 on 2019-12-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Program', '0002_remove_scientificstatues_gpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='semester_count',
        ),
    ]
