# Generated by Django 3.0.2 on 2020-01-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Program', '0003_remove_program_semester_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='scientificstatues',
            options={'base_manager_name': 'objects'},
        ),
    ]
