# Generated by Django 2.2.5 on 2020-02-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdata',
            name='isAccepted',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
