# Generated by Django 2.2.5 on 2020-03-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0004_requestdata_credit_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdata',
            name='credit_card',
            field=models.TextField(default=None, null=True),
        ),
    ]
